version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=production
    command: node dist/app/main.js

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=development
    command: npm run dev

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/usr/src/app
    command: npm run test:integration
    environment:
      - NODE_ENV=test
